### ISSUE TITLE
Feature 1: User can select a category of learning topics

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/fun-2-learn#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select a category of learning topics on the home page
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- The user will have the option to pick from three learning topics; letters, colors, and numbers.
- When the user clicks on each topic, the user will hear the topic out loud.
- The user will be able to toggle the background music on/off
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/154162847-69c88f16-7ef6-4bff-8e54-0a6a9b3811d9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component for the background
    - [x] Create a method/element for background music
    - [x] Add corresponding props{methods} to toggle music PLAYING vs PAUSED based on the state
    - [x] Create one button to toggle background music.
- [x] Create a component for the navbar
- [x] Create a component for the learning topics (home.jsx)
    - [x] render the 3 learning topics spread apart on the screen ( direction: row desktop, column mobile)
    - [x] Add sound(text-to-speech) when clicked a topic ("letters", "colors", "numbers")

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
