### ISSUE TITLE
Feature 2: User can view the letters of the alphabet

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/fun-2-learn#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- User can view the entire alphabet by clicking through a carousel
- User can hear the current letter out loud via button click
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user selects the letters learning icon, they will be able to cycle through letters in order by clicking arrows
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/154163437-c82838e0-d5e5-43c1-8e28-72b53e730084.png)
![image](https://user-images.githubusercontent.com/93749120/154163467-8ab990d2-11a6-49b8-aef4-3825dfc95637.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
### ☁️ Server

- [x] Create a route callback function to retrieve data from database
- [x] Test with HTTPie
- [x] Refactor CSS to achieve mobile/tablet/desktop responsiveness

### ⚡ Client

- [x] Create a component to swap views to the letters page on letters icon click
- [x] Create a database schema to connect letters to images and audio files
- [x] Create a carousel component within the letters page
- [x] Implement a fetch method within componentDidMount to set the state of the letters array

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
