### ISSUE TITLE
Feature 3: User can view corresponding images for each selected letter

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/fun-2-learn#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- User can click on the letter to view a word corresponding to the current letter, and click again to go back to the letter(?)
- User can hear the word out loud via button click

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will press on a letter, and the card will flip/change into a word that corresponds to the current letter. The user will then be able to play the word out loud

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/154165266-6fd23519-b3f7-494d-9bbc-1d3552ca7a7c.png)
![image](https://user-images.githubusercontent.com/93749120/154165327-8dd6fb51-c4db-4319-9242-6273846ff1d2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to include the words table via the foreign key to letterId
- [x] Create and insert the image and sound files for each word to the database words table

### ☁️ Server

- [x] Update `server/index.js` to GET and query for all the word rows from my database
- [x] Test with HTTPie
- [x] Create and insert the image and sound files for each word to public/images/words

### ⚡ Client

- [x] Refactor render method to auto-play corresponding mp3 on arrow click rather than letter click
- [x] Utilize circle section from React carousel to prepare for the word placement
- [x] Update Letters.jsx in order to show the corresponding image and play sound on letter click
    - [x]  also add logic in order to be able to flip back and forth from image to letter
- [x] Implement a fetch method in componentDidMount( ) to load content from the database to the words state Array

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
