### ISSUE TITLE
Feature 4: User can scroll through different colors

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/fun-2-learn#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- User can scroll through the colors of the rainbow (maybe other colors too) via carousel
- User can hear the current color out loud via click
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the color topic is selected, the user will be able to view different colors in a carousel, the user can then play the current color out loud. The user will also be able to click on the color and view a corresponding image

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/155435162-565ff4e0-b7b9-4f53-a3c0-d85bafa62372.png)
![image](https://user-images.githubusercontent.com/93749120/155435218-139ed829-678d-4471-992d-d12933408570.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include a imageUrl column to the colors table
- [x] Update `data.sql` to include the color names, images, and audio file routes

### ☁️ Server

- [x] Update `server/index.js` to GET the rows from the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the color carousel
- [x] Update App Component to render the colors page via route path
- [x] Implement a fetch method on componentDidMount to push objects into the state Array
- [x] Update component to display the color names
- [x] Update component to display a correlating image on color name click
- [x] Update component to display the color for each image on image click
- [x] Update component to play mp3 audio file for each color on arrow click
- [x] Update component to play mp3 audio file for each image on color click
- [x] Create a method to conditionally render background color classNames
- [x] Refactor styles.css to implement responsive layout for colors carousel

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
