### ISSUE TITLE
Feature 5: User can view number icons from 1 to 10 

### ISSUE THREAD

**Issue by MohamadAlsyouf** [MohamadAlsyouf/fun-2-learn#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- User can view the numbers from 1 to 10 on a carousel
- User can hear the current number out loud via button click
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user selects the numbers topic, they will be able to click through numbers from 1 to 10. The user will have the ability to hear the current number out loud with the click of a button
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749120/154166275-b6eecd6b-d5eb-44bb-bda7-4fa3054c899d.png)
![image](https://user-images.githubusercontent.com/93749120/154166312-197af7cd-1d14-4b14-9d97-26ea46fa6a4e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

🐘 Database
 - [x] Update data.sql to include data for the numbers table
 - [x] Create and insert the image and sound files for each number to the database numbers table

### ☁️ Server

- [x] Update `server/index.js` to GET data from the numbers table of my database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a numbers hash route to App.jsx routing method
- [x] Create a Numbers component
- [x] Update Numbers component to render a carousel
- [x] Update componentDidMount method to fetch numbers data 
- [x] Update componentDidMount to include an interval to auto play 1
- [x] Update componentWillUnmount to clear the interval set above
- [x] Update componentDidUpdate to play the next sound on arrow click

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
